# -*- coding: utf-8 -*-
"""Copy of Project: Personal Expense Tracker

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17TD7e6RfKCxsKy9iMOYPn_x3-kBhRypu
"""

import pandas as pd
def load_data(file_path):
  data=pd.read_csv(file_path)
  return data
def save_summary(summary):

  summary.to_csv("summary.csv",index=True)

import numpy as np
def total_expense(data):
  return data["Amount"].sum()
def average_expense(data):
 return np.mean(data["Amount"])
def highest_expense(data):
 return data["Amount"].max()
def lowest_expense(data):
  return data["Amount"].min()
def category_summary(data):
  return data.groupby("Category")["Amount"].sum()
def monthly_summary(data):
  data["Date"]=data["Date"].astype(str)
  data["month"]=data["Date"].str[:7]
  return data.groupby("month")["Amount"].sum()

import pandas as pd
data={
    "Date":["4-8-2026","5-8-2026","6-8-2026"],
    "Category":["food","transport","shopping"],
    "Description":["lunch","bus","shoes"],
    "Amount":[500,300,2000]
}
df=pd.DataFrame(data)
df.to_csv("expense.csv",index=False)
print("expense.csv ban ghi.")

data=load_data("expense.csv")
print("total expense:",total_expense(data))
print("average expense:",average_expense(data))
print("highest expense:",highest_expense(data))
print("lowest expense:",lowest_expense(data))
print("/nCategory wise Expense")
category=category_summary(data)
print(category)
print("/nmonthly expense")
month=monthly_summary(data)
print(month)
save_summary(category)
print("/nSummary File Save Ho ghi.")