# -*- coding: utf-8 -*-
"""Copy of Student Performance Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PQZWqrseNSyohbqi0Rdn_O0linoWA91x
"""

data={
    "Name":["Ali","Bisma","Zoha","Sara","Wali","Roman"],
    "Math":[90,89,80,99,86,98],
    "CN":[88,78,90,95,90,87],
    "opp":[87,88,76,78,98,79]
}
df=pd.DataFrame(data)
print(df)

df.head()

df.info()

df.describe()

#Add new column
df["Total"]=df["Math"]+df["CN"]+df["opp"]
print(df)

#Average Marks
df["Average"]=df["Total"]/3
print(df)

#Grade System
def grade(avg):
  if avg>=90:
    print("grade A")
  elif avg>=80:
    print("grade B")
  elif avg>=70:
    print("grade C")
  elif avg>=60:
    print("grade D")
  else:
    print("Fail")
df["Grade"]=df["Average"].apply(grade)
print(df)

import numpy as np
import pandas as pd

#NumPy
marks=np.array(df["Total"])
print("maximum:",np.nanmax(marks))
print("minimum:",np.nanmin(marks))
print("average:",np.nanmean(marks))
print("sum:",np.nansum(marks))

#Sorting
df.sort_values("Average", ascending=False)

#Filtering
df[df["Average"]>=80]

#Update Data
df.loc[0,"Math"]=85
print(df)

#Add new Student
new_student={
    "Name":"Neha",
    "Math":99,
    "CN":89,
    "opp":89,
    "total":277,
    "Average":92,
    "Grade":"A"
}
df.loc[len(df)]=new_student
print(df)

#Save CSV
df.to_csv("student_report.csv",index=False)
print("File Saved Successfully")

#Read CSV
data=pd.read_csv("student_report.csv")
print(data)